In [ ]:
!pip install ktrain

In [2]:
!pip install sentence_transformers

In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf
import ktrain
from ktrain import text

from sentence_transformers import SentenceTransformer

input_df = pd.read_csv("/content/data_0505.csv")

https://huggingface.co/shibing624/text2vec-base-multilingual

In [5]:
'''



sentences = "Diciamo NO alla pizza con l'ananas!"

sentence_embeddings = m.encode(sentences)
print("Sentence embeddings:")
print(sentence_embeddings)
'''

'\n\n\n\nsentences = "Diciamo NO alla pizza con l\'ananas!"\n\nsentence_embeddings = m.encode(sentences)\nprint("Sentence embeddings:")\nprint(sentence_embeddings)\n'

In [6]:
from sklearn.model_selection import train_test_split
m = SentenceTransformer("shibing624/text2vec-base-multilingual")

X_df = input_df.filter(["Titles"],axis=1)
Y_df = input_df.filter(["Target"],axis=1)
#print(Y_df)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/88.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/701 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/496 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
c = 384 # dim embedding
r = 500 # dim dataset

X = np.array([ [0]*c   ] *  r)
for idx,row in input_df.iterrows():
  sentence_embeddings = m.encode(row["Titles"])
  X[idx,:] = sentence_embeddings


In [8]:
t_size = 0.2

x_train, x_test, y_train, y_test = train_test_split( X, Y_df, test_size=t_size, random_state=42)

In [9]:
#x = np.array([ [0]*3   ] *  2)
#x[1,:] = [1,1,1]
#print(x.shape)
#print(x)
#

In [10]:
#model_name = 'bert-base-multilingual-uncased'       #It maps sentences to a 384 dimensional dense vector space
#transformer = text.Transformer(model_name, maxlen=384, class_names= np.array([0,1,2]))

In [11]:
y_train = y_train + 1           # VUOLE CLASSI NUMERATE DA 0
y_test = y_test + 1
#processed_train = transformer.preprocess_train(x_train, list(y_train["Target"]))
#processed_test = transformer.preprocess_test(x_train, list(y_test["Target"]))

In [12]:
#import transformers
#import torch
#
#model_id = "meta-llama/Meta-Llama-3-8B"
#
#pipeline = transformers.pipeline( "text-generation", model=model_id, model_kwargs={"torch_dtype": torch.bfloat16}, device_map="auto")
#pipeline("Hey how are you doing today?")



In [13]:
len(X[0,:])
print(len(y_train),"---",y_train["Target"].iloc[2])
print(type(y_train))
for i in range(0,len(y_train)):
  pass
  #print(y_train["Target"].iloc[i])

400 --- 1
<class 'pandas.core.frame.DataFrame'>


Tabular classification, most downloaded model:

https://huggingface.co/yzhuang/MetaTree

Random forest reference  (+Marazzina):
https://www.datacamp.com/tutorial/random-forests-classifier-python

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam, RMSprop, SGD, Adagrad

In [15]:
#to train the NN we need to convert integer output to binary array
num_classes = 3
y_train_dummy = np.zeros((len(y_train), num_classes))


for i in range(0,len(y_train)):
    class_idx = y_train.iloc[i]["Target"]  # Assuming "Target" is the column name
    y_train_dummy[i, class_idx] = 1

y_test_dummy = np.zeros((len(y_test), num_classes))
for i in range(0,len(y_test)):
  y_test_dummy[i,y_test["Target"].iloc[i]] = 1


In [16]:
y_test_dummy.shape

(100, 3)

In [ ]:
'''
model=Sequential()
model.add(Dense(units=384, activation='linear', input_dim=384))
model.add(Dense(units=200, activation='tanh'))
model.add(Dense(units=200, activation='relu'))  ##
model.add(Dense(units=200, activation='linear'))  ##
model.add(Dense(units=3, activation='sigmoid'))    #output layer
model.compile(loss='mse',
              optimizer=Adam(lr=0.0001,beta_1=0.9,beta_2=0.999))

model.fit(x_train,y_train,epochs=200,batch_size=10)  #10, 5

pred_train=model.predict(x_train)
pred_test=model.predict(x_test)
'''

In [143]:
model=Sequential()
model.add(Dense(units=384, activation='linear', input_dim=384))
model.add(Dense(units=200, activation='relu'))
model.add(Dense(units=3, activation='sigmoid'))    #output layer
model.compile(loss='mse',
              optimizer=Adam(lr=0.001,beta_1=0.9,beta_2=0.999))

model.fit(x_train,y_train,epochs=2000,batch_size=6)  #10, 5


pred_train=model.predict(x_train)
pred_test=model.predict(x_test)

Epoch 1/2000
67/67 [==============================] - 1s 3ms/step - loss: 0.9772
Epoch 2/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.9520
Epoch 3/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.9278
Epoch 4/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.9046
Epoch 5/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.8823
Epoch 6/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.8608
Epoch 7/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.8405
Epoch 8/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.8210
Epoch 9/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.8025
Epoch 10/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.7850
Epoch 11/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.7684
Epoch 12/2000
67/67 [==============================] - 0s 3ms/step - loss: 0.7527
Epoch 13/2000
67/67 [====

In [144]:
#sss = np.array( [[0,1,2], [5,3,5]] )
#for i in range(len(sss)):
#  print( sss[i,:].argmax() )
#print(sss.argmax())

In [145]:
pred_test_2 = np.zeros(pred_test.shape)
for i in range(len(pred_test)):
  pred_test_2[i, pred_test[i,:].argmax()  ] = 1

pred_train_2 = np.zeros(pred_train.shape)
for i in range(len(pred_train)):
  pred_train_2[i, pred_train[i,:].argmax()  ] = 1

In [146]:
print(pred_train.shape,"--",x_train.shape)
print(pred_test.shape,"--",x_test.shape)

print(pred_train[23,:],"--",y_train_dummy[0,:])
print(  )
for i in range(160,200):
  print(pred_train_2[i,:],"--",y_train_dummy[i,:])

(400, 3) -- (400, 384)
(100, 3) -- (100, 384)
[1. 1. 1.] -- [1. 0. 0.]

[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 0. 1.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [1. 0. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 1. 0.]
[1. 0. 0.] -- [0. 0. 1.]
[1.

In [147]:
MSE_train = np.sum(  (pred_train-y_train_dummy)**2)   /pred_train.shape[0]
MSE_test = np.sum(  (pred_test-y_test_dummy)**2)   /pred_test.shape[0]

print("MSE_train: ",MSE_train)
print("MSE_test: ",MSE_test)

MSE_train:  2.0
MSE_test:  2.0


In [148]:
MSE_train = np.sum(  (pred_train_2-y_train_dummy)**2)   /pred_train.shape[0]
MSE_test = np.sum(  (pred_test_2-y_test_dummy)**2)   /pred_test.shape[0]

print("MSE_train: ",MSE_train)
print("MSE_test: ",MSE_test)

MSE_train:  1.865
MSE_test:  1.86


In [149]:
miss_train = np.sum(  abs(pred_train_2-y_train_dummy)/2)   /pred_train.shape[0]
miss_test = np.sum(  abs(pred_test_2-y_test_dummy)/2)   /pred_test.shape[0]

print("Missclasification_train: ",miss_train)
print("Missclassification_test: ",miss_test)

Missclasification_train:  0.9325
Missclassification_test:  0.93


In [150]:
'''
model=Sequential()
model.add(Dense(units=384, activation='relu', input_dim=384))
model.add(Dense(units=200, activation='tanh'))
model.add(Dense(units=200, activation='sigmoid'))  ##
model.add(Dense(units=200, activation='linear'))  ##
model.add(Dense(units=3, activation='sigmoid'))    #output layer
model.compile(loss='mse',
              optimizer=Adam(lr=0.0001,beta_1=0.9,beta_2=0.999))

model.fit(x_train,y_train,epochs=200,batch_size=10)  #10, 5


pred_train=model.predict(x_train)
pred_test=model.predict(x_test)


MSE_train:  1.9999998185038634
MSE_test:  1.9999998080730506

MSE_train:  0.875
MSE_test:  0.7

Missclasification_train:  0.4375
Missclassification_test:  0.35

'''

"\nmodel=Sequential()\nmodel.add(Dense(units=384, activation='relu', input_dim=384))\nmodel.add(Dense(units=200, activation='tanh'))\nmodel.add(Dense(units=200, activation='sigmoid'))  ##\nmodel.add(Dense(units=200, activation='linear'))  ##\nmodel.add(Dense(units=3, activation='sigmoid'))    #output layer\nmodel.compile(loss='mse',\n              optimizer=Adam(lr=0.0001,beta_1=0.9,beta_2=0.999))\n\nmodel.fit(x_train,y_train,epochs=200,batch_size=10)  #10, 5\n\n\npred_train=model.predict(x_train)\npred_test=model.predict(x_test)\n\n\nMSE_train:  1.9999998185038634\nMSE_test:  1.9999998080730506\n\nMSE_train:  0.875\nMSE_test:  0.7\n\nMissclasification_train:  0.4375\nMissclassification_test:  0.35\n\n"